version: "3"
services:
  #db:
    #image: postgres:11
    #ports:
      #- "5432:5432"
    #environment:
      #- POSTGRES_USER=postgres
      #- POSTGRES_PASSWORD=password
      #- POSTGRES_DB=postgresdb

  web:
    build:
      context: .
    tty:
      true
    volumes:
      - "./src:/app"
    ports:
      - "8080:80"
    #depends_on:
      #- db